[project]
name = "projet-groupe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Benjamin.Dupille", email = "dupillobenji@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "iniconfig>=2.3.0",
    "psycopg>=3.3.6",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.4",
]

[project.scripts]
projet-groupe = "projet_groupe:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
